name: 'Upload to oss'
description: 'Upload files to oss'
inputs:
  key-id:
    description: 'access key ID'
    required: true
    default: ''
  key-secret:
    description: 'access key secret'
    required: true
    default: ''
  endpoint:
    description: 'endpooint'
    required: true
    default: ''
  bucket:
    description: 'bucket'
    required: true
    default: ''
  asset-path:
    description: 'file path to be uploaded'
    required: true
    default: ''
  target-path:
    description: 'file path stored on the OSS'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        for filepath in `ls ${{ inputs.asset-path }}`; do                                                                                       
          echo "filepath: ${filepath}"
          echo "asset-path: ${{ inputs.asset-path }}"
          echo "target-path: ${{ inputs.target-path }}"
          echo "before ossutil"
          ls ${{ inputs.asset-path }}
          pwd
          ossutil64 -e ${{ inputs.endpoint}} \
              -i ${{ inputs.key-id }} \
              -k ${{ inputs.key-secret }} \
              -f cp ./${filepath} oss://${{ inputs.bucket }}/${{ inputs.target-path }}/$(basename ${filepath})
          echo "after ossutil"
          pwd
          ls ${{ inputs.asset-path }}
        done
      shell: bash
