name: release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  package:
    name: build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          - centos6
          - centos7
          - centos8
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: package
        run: ./package/package.sh
      - name: output some vars
        id: vars
        run: |
          filename=$(find build/cpack_output -type f \( -iname \*.deb -o -iname \*.rpm \))
          sha256sum $filename > $filename.$SHA_EXT
          subdir=$(date -u +%Y.%m.%d)
          echo "::set-output name=filepath::$filename"
          echo "::set-output name=shafilepath::$filename.$SHA_EXT"
          echo "::set-output name=subdir::$subdir"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-v2-nightly
          path: build/cpack_output
      - name: upload package to oss
        uses: tvrcgo/upload-to-oss@v0.2.0
        with:
          key-id: LTAI4GL8kA8qApseSVGQRGxW
          key-secret: DQTbWr7pxjeTQ1NM3CU6yX4rLUCP9O
          endpoint: oss-cn-huhehaote.aliyuncs.com
          bucket: nebula-graph
          asset-path: build/cpack_output
          target-path: /package/nightly/{{ steps.vars.outputs.subdir }}
